#!/bin/zsh
set -euo pipefail

# Adapted from NoahCLR/homebrew-tap templates/release.sh (see the backport
# rule in that repo's templates/README.md). BambuCam-specific deviations:
# the Xcode project is generated by XcodeGen, and the tests are a Swift
# package (BambuKit), not an Xcode test target.
#
# Builds, signs, and publishes a release:
#   1. refuses to run on a dirty tree, runs the tests
#   2. builds Release and signs it with the stable identity (see signing-common.sh)
#   3. zips the app, pushes the version tag, creates the GitHub release
#   4. rewrites the cask in the Homebrew tap with the new version + sha256
# The version comes from CFBundleShortVersionString in the main app Info.plist.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="BambuCam.app"
APP_REPO="NoahCLR/BambuCam"
TAP_REPO="NoahCLR/homebrew-tap"
CASK_TOKEN="bambucam"

source "$ROOT_DIR/scripts/signing-common.sh"

if [[ -n "$(git -C "$ROOT_DIR" status --porcelain)" ]]; then
  echo "Working tree is not clean. Commit or stash before releasing." >&2
  exit 1
fi

VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$ROOT_DIR/BambuCam/Info.plist")"
TAG="v$VERSION"

if gh release view "$TAG" --repo "$APP_REPO" >/dev/null 2>&1; then
  echo "Release $TAG already exists on $APP_REPO. Bump CFBundleShortVersionString first." >&2
  exit 1
fi

BUILD_DIR="$(mktemp -d /tmp/bambucam-release.XXXXXX)"
trap 'rm -rf "$BUILD_DIR"' EXIT
DERIVED_DATA="$BUILD_DIR/DerivedData"
BUILT_APP="$DERIVED_DATA/Build/Products/Release/$APP_NAME"

command -v xcodegen >/dev/null || {
  echo "error: xcodegen is required (brew install xcodegen)" >&2
  exit 1
}
xcodegen generate --quiet

echo "Running tests..."
swift test --package-path "$ROOT_DIR/BambuKit"

echo "Building Release $VERSION..."
xcodebuild \
  -project "$ROOT_DIR/BambuCam.xcodeproj" \
  -scheme BambuCam \
  -configuration Release \
  -destination 'generic/platform=macOS' \
  -derivedDataPath "$DERIVED_DATA" \
  CODE_SIGNING_ALLOWED=NO \
  build

if [[ ! -d "$BUILT_APP" ]]; then
  echo "Build did not produce $BUILT_APP" >&2
  exit 1
fi

ensure_signing_identity
sign_app_bundle "$BUILT_APP"

ZIP_PATH="$BUILD_DIR/BambuCam-$VERSION.zip"
ditto -c -k --sequesterRsrc --keepParent "$BUILT_APP" "$ZIP_PATH"
SHA256="$(shasum -a 256 "$ZIP_PATH" | awk '{print $1}')"
echo "Artifact: $ZIP_PATH"
echo "SHA256:   $SHA256"

echo "Tagging $TAG and pushing..."
git -C "$ROOT_DIR" tag "$TAG" 2>/dev/null || echo "Tag $TAG already exists locally."
git -C "$ROOT_DIR" push origin HEAD "$TAG"

echo "Creating GitHub release $TAG..."
gh release create "$TAG" "$ZIP_PATH" \
  --repo "$APP_REPO" \
  --title "BambuCam $VERSION" \
  --notes "Install or upgrade with:

\`\`\`sh
brew install NoahCLR/tap/$CASK_TOKEN
xattr -dr com.apple.quarantine \"/Applications/BambuCam.app\"
\`\`\`

The \`xattr\` line clears Gatekeeper quarantine (the app is signed but not notarized)."

echo "Updating cask in $TAP_REPO..."
TAP_DIR="$BUILD_DIR/homebrew-tap"
gh repo clone "$TAP_REPO" "$TAP_DIR" -- --depth 1
mkdir -p "$TAP_DIR/Casks"
cat > "$TAP_DIR/Casks/$CASK_TOKEN.rb" <<EOF
cask "$CASK_TOKEN" do
  version "$VERSION"
  sha256 "$SHA256"

  url "https://github.com/$APP_REPO/releases/download/v#{version}/BambuCam-#{version}.zip"
  name "BambuCam"
  desc "Local-only Bambu Lab printer camera and status client"
  homepage "https://github.com/$APP_REPO"

  depends_on macos: :sequoia

  app "BambuCam.app"

  uninstall quit: "com.ncleroy.BambuCam"

  # List specific files only — never the whole Application Support directory
  # (on the dev machine it also contains the local signing key).
  zap trash: [
    "~/.bambucam",
    "~/Library/Application Support/BambuCam/config.json",
    "~/Library/Preferences/com.ncleroy.BambuCam.plist",
    "~/Library/Saved Application State/com.ncleroy.BambuCam.savedState",
  ]

  caveats <<~EOS
    BambuCam is signed with a development certificate and is not notarized,
    so Gatekeeper blocks the first launch. Either clear the quarantine flag:
      xattr -dr com.apple.quarantine "/Applications/BambuCam.app"
    or launch once, then approve it under
    System Settings > Privacy & Security > Open Anyway.
    The same applies after every brew upgrade.

    Printer access codes and certificate pins live in the macOS Keychain and
    are not removed by uninstall or zap. To remove them:
      security delete-generic-password -s com.ncleroy.BambuCam.printer-secrets
    (repeat until it reports no matching item).
  EOS
end
EOF

git -C "$TAP_DIR" add "Casks/$CASK_TOKEN.rb"
if git -C "$TAP_DIR" diff --cached --quiet; then
  echo "Cask unchanged; nothing to push to the tap."
else
  git -C "$TAP_DIR" commit -m "$CASK_TOKEN $VERSION"
  git -C "$TAP_DIR" push
fi

echo ""
echo "Released BambuCam $VERSION."
echo "Install with: brew install NoahCLR/tap/$CASK_TOKEN"
